# Generated by Django 6.0.4 on 2026-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='full_time',
            field=models.BooleanField(default=False, verbose_name='Available Full Time'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_civil_defence',
            field=models.BooleanField(default=False, verbose_name='Civil Defence'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_driving',
            field=models.BooleanField(default=False, verbose_name='Has Driving License'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_first_aid',
            field=models.BooleanField(default=False, verbose_name='First Aid Trained'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_ncc',
            field=models.BooleanField(default=False, verbose_name='NCC Member'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_ngo',
            field=models.BooleanField(default=False, verbose_name='NGO Member'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_nss',
            field=models.BooleanField(default=False, verbose_name='NSS Member'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_red_cross',
            field=models.BooleanField(default=False, verbose_name='Red Cross'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_scouts',
            field=models.BooleanField(default=False, verbose_name='Scouts / Guides'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='has_swimming',
            field=models.BooleanField(default=False, verbose_name='Can Swim'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='help_types',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='languages',
            field=models.CharField(default='Malayalam, English', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='organization',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='other_organisation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='profession',
            field=models.CharField(choices=[('student', 'Student'), ('doctor', 'Doctor / Medical Professional'), ('nurse', 'Nurse / Paramedic'), ('engineer', 'Engineer'), ('teacher', 'Teacher'), ('driver', 'Driver'), ('cook', 'Cook'), ('social_worker', 'Social Worker'), ('govt_employee', 'Government Employee'), ('ngo_worker', 'NGO Worker'), ('police', 'Police / Military'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='available_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='id_proof_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='skills',
            field=models.CharField(default='', max_length=500),
        ),
    ]
