# Generated by Django 6.0.4 on 2026-06-14 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_contact_person_customuser_district_and_more'),
        ('camps', '0003_emergencyalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camp_heads', to='camps.camp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('panchayath_staff', 'Panchayath Staff'), ('camp_head', 'Camp Head')], default='donor', max_length=20),
        ),
    ]
