# Generated by Django 6.0.2 on 2026-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_camp_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('admin', 'Admin'), ('panchayath_staff', 'Panchayath Officer'), ('field_officer', 'Field Officer'), ('district_officer', 'District Officer'), ('camp_head', 'Camp Head')], default='donor', max_length=20),
        ),
    ]
