# Generated by Django 6.0.2 on 2026-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_employee_id_customuser_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approved_by_field_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='approved_by_panchayath',
            field=models.BooleanField(default=False),
        ),
    ]
