# Generated by Django 6.0.4 on 2026-07-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Registration'), ('approve_staff', 'Staff Approved'), ('reject_staff', 'Staff Rejected'), ('approve_volunteer', 'Volunteer Approved'), ('allocate_funds', 'Funds Allocated'), ('add_camp', 'Camp Added'), ('update_camp', 'Camp Updated'), ('add_need', 'Need Reported'), ('verify_need', 'Need Verified'), ('donate_money', 'Money Donated'), ('donate_item', 'Item Donated'), ('update_delivery', 'Delivery Updated'), ('other', 'Other')], max_length=30),
        ),
    ]
