# Generated by Django 6.0.4 on 2026-05-30 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camps', '0003_emergencyalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_phone', models.CharField(max_length=15)),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_status', models.CharField(choices=[('registered', 'Registered'), ('at_panchayath', 'At Panchayath'), ('in_transit', 'In Transit'), ('at_camp', 'Received at Camp'), ('delivered', 'Delivered')], default='registered', max_length=20)),
                ('panchayath_name', models.CharField(blank=True, max_length=150)),
                ('panchayath_address', models.TextField(blank=True)),
                ('dispatched_by', models.CharField(blank=True, max_length=150)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
                ('tracking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camps.camp')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('allocated', 'Allocated to Camp'), ('spent', 'Spent')], default='received', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('camp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='camps.camp')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
