# Generated by Django 6.0.4 on 2026-05-31 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdonation',
            name='panchayath',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'panchayath_staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdonation',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
