# Generated by Django 6.0.2 on 2026-04-25 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=100)),
                ('people_count', models.PositiveIntegerField(default=0)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('quantity_needed', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='units', max_length=50)),
                ('priority', models.CharField(choices=[('urgent', '🔴 Urgent'), ('normal', '🟡 Normal'), ('low', '🟢 Low')], default='normal', max_length=10)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to='camps.camp')),
            ],
        ),
    ]
