# Generated by Django 6.0.4 on 2026-06-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0004_camp_created_by_camp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Panchayath Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
    ]
