# Generated by Django 6.0.2 on 2026-06-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0005_need_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='verified_by_field_officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='need',
            name='verified_by_panchayath',
            field=models.BooleanField(default=False),
        ),
    ]
