# Generated by Django 6.0.4 on 2026-06-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0008_need_verified_by_district_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='verified_by_district_officer',
        ),
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Panchayath Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='verified', max_length=20),
        ),
    ]
